name: Release

on:
  push:
    branches:
      - 'alpha'
      - 'beta'
      - 'main'

jobs:
  release-config:
    name: Release @trezy-studios/react-pixi-fiber
    uses: ./.github/workflows/release-base.yml
    with:
      packageName: '@trezy-studios/react-pixi-fiber'
    secrets: inherit
